name: Backend Deployment

on:
  push:
    paths:
      - 'backend/**'
      - 'scripts/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run packaging script
        run: |
          chmod +x scripts/package-backend.sh
          ./scripts/package-backend.sh

      - name: Run deployment script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          chmod +x scripts/deploy-backend.sh
          ./scripts/deploy-backend.sh
